version: "3.8"
services:
  traefik:
    image: traefik:v2.10.4
    container_name: "traefik"
    command:
      - "--providers.docker.constraints=Label(`traefik.constraint`,`${PROJECT_NAME}`)"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
      - "--entryPoints.admin.address=:3030"
    ports:
      # hasura/services
      - "1337:1337"
      # traefik interface
      - "9090:8080"
      # dashboard
      - "3030:3030"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  postgres:
    image: postgres:15.4
    restart: always
    # Prevent PostgreSQL JIT from slowing down SQL queries
    command: postgres -c jit=off
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    # ports:
    #   - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    # depends_on:
    # - 'postgres'
    restart: always
    expose:
      - 8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: error
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      ## enable debugging mode. It is recommended to disable this in production
      # HASURA_GRAPHQL_DEV_MODE: 'true'
      # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      # HASURA_GRAPHQL_METADATA_DEFAULTS: '{'backend_configs':{'dataconnector':{'athena':{'uri':'http://data-connector-agent:8081/api/v1/athena'},'mariadb':{'uri':'http://data-connector-agent:8081/api/v1/mariadb'},'mysql8':{'uri':'http://data-connector-agent:8081/api/v1/mysql'},'oracle':{'uri':'http://data-connector-agent:8081/api/v1/oracle'},'snowflake':{'uri':'http://data-connector-agent:8081/api/v1/snowflake'}}}}'
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://localhost:8080/healthz > /dev/null 2>&1
      timeout: 60s
      interval: 30s
      start_period: 90s
    labels:
      - "traefik.constraint=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(${HOST}) && PathPrefix(`/`)"
      - "traefik.http.routers.hasura.entrypoints=web"
  auth:
    image: hasura-auth:0.0.0-dev
    depends_on:
      - postgres
      - graphql-engine
    restart: always
    volumes:
      - ./emails:/app/email-templates
    environment:
      AUTH_HOST: ${AUTH_HOST}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      AUTH_SERVER_URL:
        ${AUTH_SERVER_URL}
        #AUTH_API_PREFIX: ${AUTH_API_PREFIX}
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL}
      AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS: ${AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS}
      AUTH_PROVIDER_GITHUB_ENABLED: ${AUTH_PROVIDER_GITHUB_ENABLED}
      AUTH_PROVIDER_GITHUB_CLIENT_ID: ${AUTH_PROVIDER_GITHUB_CLIENT_ID}
      AUTH_PROVIDER_GITHUB_CLIENT_SECRET: ${AUTH_PROVIDER_GITHUB_CLIENT_SECRET}
      # AUTH_PROVIDER_GITHUB_AUTHORIZATION_URL=''
      # AUTH_PROVIDER_GITHUB_TOKEN_URL=''
      # AUTH_PROVIDER_GITHUB_USER_PROFILE_URL=''
      AUTH_PROVIDER_GITHUB_SCOPE: ${AUTH_PROVIDER_GITHUB_SCOPE}
      # apple
      AUTH_PROVIDER_APPLE_ENABLED: ${AUTH_PROVIDER_APPLE_ENABLED}
      AUTH_PROVIDER_APPLE_CLIENT_ID: ${AUTH_PROVIDER_APPLE_CLIENT_ID}
      AUTH_PROVIDER_APPLE_TEAM_ID: ${AUTH_PROVIDER_APPLE_TEAM_ID}
      AUTH_PROVIDER_APPLE_KEY_ID: ${AUTH_PROVIDER_APPLE_KEY_ID}
      AUTH_PROVIDER_APPLE_PRIVATE_KEY: ${AUTH_PROVIDER_APPLE_PRIVATE_KEY}
      AUTH_PROVIDER_APPLE_SCOPE: ${AUTH_PROVIDER_APPLE_SCOPE}
      # AUTH_ACCESS_TOKEN_EXPIRES_IN: 86400 #(1 day)
      AUTH_ACCESS_TOKEN_EXPIRES_IN: 3801600 #(44 day)
      # AUTH_REFRESH_TOKEN_EXPIRES_IN: 2592000 #(30 days)
      AUTH_REFRESH_TOKEN_EXPIRES_IN: 10368000 #(120 days)
      # AUTH_ACCESS_TOKEN_EXPIRES_IN: 30
      # AUTH_REFRESH_TOKEN_EXPIRES_IN: 60
      # AUTH_CLIENT_URL: ${AUTH_CLIENT_URL:-http://localhost:3000}
      # AUTH_SMTP_HOST: mailhog
      # AUTH_SMTP_PORT: 1025
      # AUTH_SMTP_USER: user
      # AUTH_SMTP_PASS: password
      # AUTH_SMTP_SENDER: mail@example.com
      # 关闭邮箱验证
      AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED: false
    expose:
      - 4000
    labels:
      - "traefik.constraint=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth"
      - "traefik.http.routers.auth.rule=Host(${HOST}) && PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.auth.middlewares=strip-auth@docker"
      - "traefik.http.routers.auth.entrypoints=web"
  storage:
    image: nhost/hasura-storage:0.4.1
    depends_on:
      - postgres
      - graphql-engine
      - minio
    restart: always
    expose:
      - 8000
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
      HASURA_METADATA: 1
      HASURA_ENDPOINT: http://graphql-engine:8080/v1
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      S3_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      S3_SECRET_KEY: ${STORAGE_SECRET_KEY}
      S3_ENDPOINT: http://minio:8484
      S3_BUCKET: nhost
      POSTGRES_MIGRATIONS: 1
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres?sslmode=disable
    labels:
      - "traefik.constraint=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(${HOST}) && PathPrefix(`/v1/storage`)"
      - "traefik.http.routers.storage.entrypoints=web"
      # Rewrite the path so it matches with the new storage API path introduced in hasura-storage 0.2
      - "traefik.http.middlewares.strip-suffix.replacepathregex.regex=^/v1/storage/(.*)"
      - "traefik.http.middlewares.strip-suffix.replacepathregex.replacement=/v1/$$1"
      - "traefik.http.routers.storage.middlewares=strip-suffix@docker"
    command: serve
  functions:
    image: nhost/functions:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-functions.stripprefix.prefixes=/v1/functions"
      - "traefik.http.routers.functions.rule=Host(`${PROXY_HOST}`, `localhost`) && PathPrefix(`/v1/functions`)"
      - "traefik.http.routers.functions.middlewares=strip-functions@docker"
      - "traefik.http.routers.functions.entrypoints=web"
    restart: always
    expose:
      - 3000
    volumes:
      - .:/opt/project
      - functions_node_modules:/opt/project/node_modules
      - /opt/project/data/
      - /opt/project/initdb.d/
  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    entrypoint: sh
    command: -c 'mkdir -p /data/nhost && /opt/bin/minio server --address :8484 /data'
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    ports:
      - ${MINIO_PORT:-8484}:8484
    volumes:
      - ./data/minio:/data
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      SMTP_USER: ${AUTH_SMTP_USER:-user}
      SMTP_SECURE: "${AUTH_SMTP_SECURE:-false}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    ports:
      - ${AUTH_SMTP_PORT:-1025}:1025
      - 8025:8025
    volumes:
      - ./data/mailhog:/maildir
  dashboard:
    image: nhost/dashboard:0.21.1
    environment:
      NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL: ${NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL}
      NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL: ${NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL}
      NEXT_PUBLIC_NHOST_HASURA_API_URL: ${NEXT_PUBLIC_NHOST_HASURA_API_URL}
      NEXT_PUBLIC_NHOST_ADMIN_SECRET: ${NEXT_PUBLIC_NHOST_ADMIN_SECRET}
      NEXT_PUBLIC_NHOST_AUTH_URL: ${NEXT_PUBLIC_NHOST_AUTH_URL}
      NEXT_PUBLIC_NHOST_GRAPHQL_URL: ${NEXT_PUBLIC_NHOST_GRAPHQL_URL}
      NEXT_PUBLIC_NHOST_STORAGE_URL: ${NEXT_PUBLIC_NHOST_STORAGE_URL}
      NEXT_PUBLIC_NHOST_FUNCTIONS_URL: ${NEXT_PUBLIC_NHOST_FUNCTIONS_URL}
      NEXT_PUBLIC_NHOST_CONFIGSERVER_URL: ${NEXT_PUBLIC_NHOST_CONFIGSERVER_URL}
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nhost.rule=Host(`${NHOST_HOST}`)"
      - "traefik.http.routers.nhost.entrypoints=admin"
      # If you would like to protect your dashboard with a username and password if it is publicly-facing, uncomment and fill in the following lines below according to the documentation at https://doc.traefik.io/traefik/middlewares/http/basicauth/
      #- "traefik.http.routers.nhost.middlewares=auth"
      #- "traefik.http.middlewares.auth.basicauth.users=
volumes:
  functions_node_modules:
